export enum Category {
  BIKEGEAR="BIKES & GEAR",
  TRAINING="TRAINING",
  REPAIR="REPAIR",
  HEALTHNUTRITION="HEALTH & NUTRITION",
}
export enum CategoryId {
  BIKEGEAR=19,
  TRAINING=20,
  REPAIR=21,
  HEALTHNUTRITION=1,
}
export enum BikesCategory {
  MOUNTAIN="MOUNTAIN BIKES",
  ROAD="ROAD BIKES",
  TOURING="TOURING BIKES",
  CITY="CITY BIKES",
  KID="KID BIKES",
}