export enum Category {
  BIKEGEAR = "BIKES & GEAR",
  TRAINING = "TRAINING",
  REPAIR = "REPAIR",
  HEALTHNUTRITION = "HEALTH & NUTRITION",
}
export enum CategoryId {
  BIKEGEAR = 19,
  TRAINING = 20,
  REPAIR = 21,
  HEALTHNUTRITION = 1,
}